rawg.api.key=a27c502d9b114cde87e03e215a3d39e3

server.port=8080

# Actuator / Observabilidade
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=playsync
